### ISSUE TITLE
Error: Received unexpexted PDU from server

### ISSUE THREAD

**Issue by saalty303** [emrebekar/node-red-contrib-opcda-client#11]
Hello all!

I'm running Node-Red on Windows 10 and it is connected to OPC DA server which is installed on another machine with Windows XP. I can read data from the server with **opcda-read** node but sometimes I got an error message mentioned in title. I cannot recognise what can cause this error message but only server restart solve it (I mean full Windows restart on server side). I tried to restart only Node-Red on the client machine as the whole Windows as well but after the restart the issue still exist. On the picture bellow you can see the screenshot from the command promt:

![Képkivágás](https://user-images.githubusercontent.com/94721231/142720501-fa64df78-4043-44f0-a940-0737500cbc83.JPG)

When issue happens I'm not able to read out data normally with other client software installed on the same client machine (OPC Scout from Siemens) even if the server looks running normally.
Can you help me how to solve this issue? Restarting the server side Windows sadly cannot be an option.

greetings,

saalty

**Comment by emrebekar** [comment]
Hi.

Have you done the configuration of dcom settings? Because you cannot
connect remote opc without dcom.

20 Kas 2021 Cmt 12:10 tarihinde saalty303 ***@***.***> şunu
yazdı:

**Comment by saalty303** [comment]
Yes I do, Connecton estabilished and I was able to read out data from the server, but after a while (as I wrote I don't know why) the status of the **opcda-read** node is connecting and I got messages like on attached picture. Once again, connection wroked well and reading data is workinf for a while, until this error appears....
