### ISSUE TITLE
Error: Received unexpected PDU from server

### ISSUE THREAD

**Issue by saalty303** [emrebekar/node-red-contrib-opcda-client#12]
Hello all!

I'm running Node-Red on Windows 10 and it is connected to OPC DA server which is installed on another machine with Windows XP. I can read data from the server with **opcda-read** node but sometimes I got an error message mentioned in title. I cannot recognise what can cause this error message but only server restart solve it (I mean full Windows restart on server side). I tried to restart only Node-Red on the client machine as the whole Windows as well but after the restart the issue still exist. On the picture bellow you can see the screenshot from the command promt:

![Picture](https://user-images.githubusercontent.com/94721231/142720816-a4b2a173-947c-4263-8a1e-f6297a1d8b65.JPG)

When issue happens I'm not able to read out data normally with other client software installed on the same client machine (OPC Scout from Siemens) even if the server looks running normally.
Can you help me how to solve this issue? Restarting the server side Windows sadly cannot be an option.

greetings,

saalty

**Comment by Jaimenms** [comment]
+1

**Comment by Jaimenms** [comment]
I have the same error. @saalty303, could you solve it?

**Comment by saalty303** [comment]
@Jaimenms it was a server side problem. It happened always, but when it depended of the amount of the data and/or cycle time. With larger amount of data or lower cycle time caused it occurs faster. If I sropped opc da service in Windows then it started again automatically and everything goes well. I made a batch file with taskkill instruction and executed it daily

**Comment by emrebekar** [comment]
Hi.
Please be sure that you configure your dcom settings first. Maybe one option is to install the matrikon simulator server to same machine with OPC server that you want to connect and try to connect to the Matrikon Simulator. Then everything is fine, there is some another problem that we search with.

https://www.matrikonopc.com/support/docs/MatrikonOPC-Windows-XP-DCOM-Configuration.pdf
