### ISSUE TITLE
Clsid syntax is invalid

### ISSUE THREAD

**Issue by PaFu99** [emrebekar/node-red-contrib-opcda-client#9]
Hello, I have a Softing Opc DA server that works without problems and the connection to the client also works without any problems. However, the connection to node-red does not work. I use Windows 10, the DCOM settings are also made correctly and the PC does not belong to any domain. I keep getting this error no matter what I try. 
Can someone please help me and tell me what I did wrong or what you did to make it work? 

![Github Fehler](https://user-images.githubusercontent.com/79148231/129180739-c435342d-f615-46d5-89b8-1e7381d76827.png)

**Comment by emrebekar** [comment]
Can you connect over another OPC DA client like Matrikon Opc Browser in same environment with Node-RED?

**Comment by PaFu99** [comment]
I deleted everything (NodeRed etc.) and downloaded it again. Now it works "locally". With these settings.

![image](https://user-images.githubusercontent.com/79148231/129336920-13f7106d-545f-4054-a83f-f0afe727660c.png)

Still have problems via the network it is probably due to the VMWare or DCOM settings.
Does anyone have a good/working template for the DCOM settings?

**Comment by PaFu99** [comment]
It's pretty weird. If I have the source of the OPC data (PLC) on a switch in the network, the data transmitted from the OPC server to NodeRed, works locally but not on another PC in the network. If I connect the PLC to the PC directly, it works too. 
(Sketch to aid understanding. Number 1 should work but it doesn't. 2 and 3 works but is not enough.)

![image](https://user-images.githubusercontent.com/79148231/129338154-bb91786d-388f-454e-9bb2-4d60b1711d13.png)

i don't think that's a problem with node-red-contrib-opcda-client but maybe someone can help me anyway.

**Comment by PaFu99** [comment]
I found the problem. It was the antivirus software. It has blocked the OPC data, or rather it has blocked the port via which the OPC data is transmitted. Therefore it worked locally but no longer in the network.
